name: flutter_Canada
description: Canada community building next gen apps. Canada Flutter Group is formed to bring people together who are using Flutter to create beautiful apps, looking to learn mobile development and making lasting connections.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.3
  url_strategy: ^0.2.0
  cached_network_image: ^3.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf
        - asset: fonts/SourceCodePro-Regular.ttf
          weight: 700
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf

  assets:
    - assets/meetup.png
    - assets/slack_white.png
    - assets/github.png
    - assets/goals.png
    - assets/conference_call.png
    - assets/open_source.png
    - assets/pair_programming.png
    - assets/pixel_heart_canada_2.png
    - assets/preview.png
    - assets/vancity.png
    - assets/community/
    - assets/social/
